symbols_coinbase = ['MKR/USD',
'LRC/USD',
'1INCH/USD', 'WBTC/USD',
'MLN/USD',

'KNC/USD',
'LOOM/USDC',
'ALGO/USD',
'GTC/USD',
'OXT/USD',
'BTC/USDC',
'DASH/USD',
'BAT/USD',
'CELO/USD',
'ADA/USDC',
'BAT/USDC',

'GNT/USDC',
'XTZ/USD',
'YFI/USD',
'BTC/USD',
'CTSI/USD',
'CRV/USD',
'ENJ/USD',
'ICP/USDT',
'MANA/USDC',
'EOS/USD',
'ETH/USDC',
'LTC/USD',
'FIL/USD',
'NKN/USD',
'ETH/USD',
'TRB/USD',
'ATOM/USD',

'NMR/USD',

'ZRX/USD',
'STORJ/USD',
'OMG/USD',

'SUSHI/USD',
'XLM/USD',
'REP/USD',
'MIR/USD',
'MATIC/USD',
'GRT/USD',
'REN/USD',

'BCH/USD',
'BAND/USD',

'ETH/USDT',
'RLC/USD',
'ICP/USD',


'AMP/USD',
'BAL/USD',

'NU/USD',
'OGN/USD',
'BNT/USD',
'DOGE/USDT',
'DOGE/USD',

'FORTH/USD',
'SKL/USD',

'ETC/USD',

'LINK/USD',
'MANA/USD',
'ZEC/USDC',

'AAVE/USD',

'ANKR/USD',
'DNT/USDC',

'ADA/USD',
'COMP/USD',
'ZEC/USD',

'BTC/USDT',

'SNX/USD',
'UNI/USD',
'CVC/USDC']


#KCOIN
symbols_kucoin = ['BTC/USDT','ETH/USDT','XRP/USDT','ADA/USDT','DOGE/USDT','LUNA/USDT'
,'VET/USDT','MATIC/USDT','ICP/USDT','DOT/USDT','TEL/USDT','KCS/USDT','EOS/USDT'
,'LTC/USDT','LINK/USDT','VRA/USDT','XLM/USDT','TRX/USDT','ALGO/USDT','SHIB/USDT'
,'KSM/USDT','BCH/USDT','TRIAS/USDT','XRP/USDT','ATOM/USDT','AAVE/USDT','THETA/USDT'
,'GRT/USDT','BTT/USDT','XDC/USDT','MIR/USDT','CHZ/USDT','AXS/USDT','SUSHI/USDT','CQT/USDT'
,'LITH/USDT','KOK/USDT','IOTX/USDT','BOSON/USDT','HTR/USDT','XMR/USDT','FORESTPLUS/USDT','ADA3S/USDT'
,'KAR/USDT','SNX/USDT','SKEY/USDT','OMG/USDT','CRV/USDT','ZORT/USDT','BUY/USDT'
,'MASK/USDT','LABS/USDT','SAND/USDT','STRONG/USDT','EWT/USDT','ARPA/USDT','RFOX/USDT'
,'MANA/USDT','AXC/USDT']

symbols_cex = ["ADA/USD",'BAT/USD','BCH/USD','BTC/USD','DOGE/USD','ETH/USD','GUSD/USD','LINK/USD','LTC/USD','MATIC/USD',
'UNI/USD','XLM/USD','ZRX/USD',]

symbols_kraken = ['BTC/USD','ETH/USD','MATIC/USD','SOL/USD','ADA/USD','DOT/USD','ATOM/USD','LINK/USD','DOGE/USD','LUNA/USD',
'AAVE/USD','MANA/USD','OMG/USD','LTC/USD','OCEAN/USD','XTZ/USD','BAT/USD','ANT/USD','CRV/USD','SHIB/USD','UNI/USD',
'XMR/USD','ALGO/USD','AVAX/USD','XLM/USD','ZEC/USD','FIL/USD','FLOW/USD','COMP/USD','SNX/USD','EOS/USD','ENJ/USD',
'KAVA/USD','SC/USD','KEEP/USD','KSM/USD','STORJ/USD','BCH/USD','YFI/USD','NANO/USD','AXS/USD','TRX/USD','DASH/USD',
'OXT/USD','ICX/USD','ETC/USD','WAVES/USD','QTUM/USD','LSK/USD','CHZ/USD','KNC/USD','BAL/USD','MLN/USD',
'REPV2/USD','GNO/USD','REP/USD','TBTC/USD']